/**
 * Caddy Configuration Generator
 *
 * Produces per-site Caddyfile snippets for customer domains.
 *
 * VPS layout expected:
 *   /var/www/sites/{domain}/        ← static files for this site
 *   /etc/caddy/sites/{domain}.caddy ← per-site Caddyfile snippet
 *   /etc/caddy/Caddyfile            ← main Caddyfile (must import /etc/caddy/sites/*.caddy)
 *
 * Caddy handles automatic HTTPS via Let's Encrypt — no manual cert management needed.
 * HTTP→HTTPS redirect is automatic when a domain is specified (no port qualifier).
 */

// ─── Per-site Caddyfile snippet ───────────────────────────────────────────────

/**
 * Generate a Caddyfile snippet for a single customer domain.
 * Caddy will automatically:
 *   1. Provision a TLS certificate from Let's Encrypt
 *   2. Redirect HTTP → HTTPS
 *   3. Serve the static files from the site root
 */
export function generateSiteCaddyConfig(domain: string): string {
  return `# Auto-generated by eve-for-hire — do not edit manually
${domain} {
  root * /var/www/sites/${domain}
  file_server
  encode gzip

  header {
    X-Content-Type-Options nosniff
    X-Frame-Options DENY
    Referrer-Policy strict-origin-when-cross-origin
  }

  log {
    output file /var/log/caddy/${domain}.log {
      roll_size 10mb
      roll_keep 5
    }
  }
}
`;
}

/**
 * Path on the VPS where per-site Caddy configs live.
 */
export function remoteSiteConfigPath(domain: string): string {
  return `/etc/caddy/sites/${domain}.caddy`;
}

/**
 * Path on the VPS where site static files live.
 */
export function remoteSiteRootPath(domain: string): string {
  return `/var/www/sites/${domain}`;
}

// ─── Main Caddyfile bootstrap ─────────────────────────────────────────────────

/**
 * The main Caddyfile that must exist on the VPS.
 * It imports all per-site configs from the sites/ directory.
 *
 * This is written once during the first deploy; subsequent deploys only write
 * the per-site snippet and reload Caddy.
 */
export const MAIN_CADDYFILE = `# Eve-for-hire — main Caddyfile
# Per-site configs are in /etc/caddy/sites/*.caddy
import /etc/caddy/sites/*.caddy
`;

/**
 * Shell commands to run on the VPS before the first site can be deployed.
 * Returns an array of commands in dependency order.
 * These are idempotent — safe to re-run if already set up.
 */
export function bootstrapCommands(): string[] {
  return [
    // Ensure site directories exist.
    'mkdir -p /var/www/sites',
    // Ensure Caddy sites config directory exists.
    'mkdir -p /etc/caddy/sites',
    // Ensure Caddy log directory exists.
    'mkdir -p /var/log/caddy',
    // Write main Caddyfile only if it doesn't already exist.
    `[ -f /etc/caddy/Caddyfile ] || printf '%s' '${MAIN_CADDYFILE.replace(/'/g, "'\\''")}' > /etc/caddy/Caddyfile`,
  ];
}
